version: "3.8"
services:
  build-agent:
    image: {PRIVATE_REPO}/teamcity-agent
    user: root
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
    environment:
      - SERVER_URL:{URL}
      - DOCKER_IN_DOCKER:start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dock/containers/teamcity-agent/volumes/conf:/data/teamcity_agent/conf
      - /home/dock/containers/teamcity-agent/volumes/work:/opt/buildagent/work
      - /home/dock/containers/teamcity-agent/volumes/temp:/opt/buildagent/temp
      - /home/dock/containers/teamcity-agent/volumes/tools:/opt/buildagent/tools
      - /home/dock/containers/teamcity-agent/volumes/plugins:/opt/buildagent/plugins
      - /home/dock/containers/teamcity-agent/volumes/system:/opt/buildagent/system

